library(shiny)
library(shinythemes)
library(DT)
library(stringi)
library(shinyWidgets)
shinyUI(fluidPage(
  theme = shinytheme("cerulean"),
  titlePanel(div("Erreger- und Resistenzstatistik",
                 img(height = 43, width = 20, src = "white.png",class="pull-right"),
                 img(height = 43, width = 50, src = "UKM.png",class="pull-right")),
                 windowTitle="Resistenz-Analyse"
  ),
  sidebarPanel(
    shinyjs::useShinyjs(),
    tabsetPanel(id="config",
                tabPanel("Input",
                         br(),
                         column(4,offset = 10,actionButton('do_clear',"RESET",class = "btn-warning")),
                         br(),
                         h4("Input"),
                         radioButtons("ownData",label="",choices=c("Eigene Daten einlesen","Demo Daten laden"),
                                      selected = "Eigene Daten einlesen",inline = T),
                         br(),
                         uiOutput("inputFileUI"),
                         uiOutput("sepInputUI"),
                         br(),
                         actionButton('do_in',"File einlesen",class = "btn-primary"),
                         hr(),
                         h4(textOutput("columnUI0")),
                         tags$head(
                           tags$style(type="text/css", 
                                      "#inline label.control-label, #inline .selectize-control.single { 
         display: table-cell; 
         text-align: left; 
         vertical-align: middle; 
      } 
      #inline label.control-label {
        padding-right: 20px;
      }
      #inline .form-group { 
        display: table-row;
      }
      #inline .selectize-control.single div.item {
        padding-right: 150px;
      }")
                         ),
                         
                         tags$div(id = "inline", uiOutput("columnUI1")),
                         tags$div(id = "inline", uiOutput("columnUI2")),
                         tags$div(id = "inline", uiOutput("columnUI3")),
                         tags$div(id = "inline", uiOutput("columnUI4")),
                         tags$div(id = "inline", uiOutput("columnUI4b")),
                         tags$div(id = "inline", uiOutput("columnUI42")),
                         tags$div(id = "inline", uiOutput("columnUI5")),
                         h6(textOutput("columnUI6")),
                         br(),
                         uiOutput("do_in2UI")
                         
                ),
      tabPanel("Erregerstatistik",
               hr(),
               h4(textOutput("anweisung0pre")),
               uiOutput("erregerstatUI1"),
               uiOutput("erregerstatUI2"),
               uiOutput("erregerstatUI3.2"),
               uiOutput("erregerstatUI4"),
               #h6("Bei der Auswahl von mehr als einem Jahr, Material oder Klinik/Fachbereich werden die einzelnen Ergebnisse aufsummiert. 
              #    Nur die Summe wird berichtet."),
               uiOutput("erregerstatUI4b"),
               uiOutput("erregerstatUI4c"),
               hr(),
               uiOutput("erregerstatUI5")),
      tabPanel("Resistenzstatistik",
               hr(),
               h4(textOutput("anweisung1pre")),
               #h4(textOutput("anweisung0")),
               #uiOutput("zusammenfassung_erstellenUI"),
               #hr(),
               uiOutput("statistikUI1"),
               uiOutput("statistikUI2"),
               uiOutput("statistikUI3.2"),
               uiOutput("statistikUI4"),
               #h6("Bei der Auswahl von mehr als einem Jahr, Material oder Klinik/Fachbereich werden die einzelnen Ergebnisse aufsummiert. 
              #    Nur die Summe wird berichtet."),
               uiOutput("statistikUI4c"),
               uiOutput("statistikUI3"),
               hr(),
               uiOutput("statistikUI5"),
               hr(),
               uiOutput("statistikUI6")
      ),
      tabPanel("Trend-Analyse",
               hr(),
               h4(textOutput("anweisung4pre")),
               uiOutput("trendUI1"),
               uiOutput("trendUI3.2"),
               uiOutput("trendUI4"),
               #h6("Bei der Auswahl von mehr als einem Material oder Klinik/Fachbereich werden die einzelnen Ergebnisse aufsummiert. 
              #    Nur die Summe wird berichtet."),
               uiOutput("trendUI4c"),
               uiOutput("trendUI3"),
               uiOutput("trendUI3.3"),
               hr(),
               uiOutput("trendUI5"),
               hr(),
               uiOutput("trendUI6")
      ),
                   navbarMenu("Cluster-Analyse",
      tabPanel("Interaktiv",
               hr(),
               h4(textOutput("anweisung2pre")),
               uiOutput("bakteriumUIinitial"),
               h4(textOutput("anweisung")),
               uiOutput("bakteriumUI0a"),
               uiOutput("bakteriumUI0b"),
               uiOutput("bakteriumUI0c"),
               hr(),
               uiOutput("bakteriumUI0"),
               hr(),
               uiOutput("bakteriumUI1"),
               uiOutput("bakteriumUI2"),
               uiOutput("bakteriumUI3"),
               uiOutput("bakteriumUI4"),
               uiOutput("klinikUI1"),
               uiOutput("klinikUI2"),
               uiOutput("klinikUI3"),
               hr(),
               uiOutput("analyseUI")
      ),
      tabPanel("Export",
               hr(),
               h4(textOutput("anweisung3pre")),
               uiOutput("downloadUIinitial"),
               h4(textOutput("anweisung2")),
               uiOutput("downloadUI1"),
               uiOutput("downloadUI2"),
               hr(),
               uiOutput("downloadUIbak0a"),
               uiOutput("downloadUIbak0b"),
               uiOutput("downloadUIbak0c"),
               hr(),
               uiOutput("downloadUI3"),
               hr(),
               uiOutput("downloadUIbak1"),
               uiOutput("downloadUIbak1b"),
               uiOutput("downloadUIbak2"),
               uiOutput("downloadUIbak3"),
               uiOutput("downloadUIbak3b"),
               uiOutput("downloadUIbak3c"),
               uiOutput("downloadUIbak3d"),
               uiOutput("downloadUIbak3e"),
               uiOutput("downloadUIbak3f"),
               uiOutput("downloadUIbak3g"),
               uiOutput("downloadUIbak3h"),
               uiOutput("downloadUIbak4"),
               hr(),
               uiOutput("downloadUIklinik1"),
               uiOutput("downloadUIklinik1b"),
               uiOutput("downloadUIklinik2"),
               uiOutput("downloadUIklinik3"),
               uiOutput("downloadUIklinik3b"),
               uiOutput("downloadUIklinik3c"),
               uiOutput("downloadUIklinik3d"),
               hr(),
               uiOutput("downloadUI4"))
      ),
      tabPanel("Info",
               hr(),
               h4(htmlOutput("text_info2h")),
               hr(),
               h4(textOutput("text_info1")),
               h5(textOutput("text_info2a")),
               hr(),
               h4(textOutput("text_info1b")),
               h5(textOutput("text_info2c")),
               hr(),
               h4(textOutput("text_info2d")),
               h5(textOutput("text_info2b")),
               hr(),
               br(),
               br(),
               h6(textOutput("text_info2g"))
      )
    )
    
  ),
  mainPanel(
    shinyjs::useShinyjs(),
    tabsetPanel(id="main",
                tabPanel("Log",
                         div(id = "text")
                ),
      tabPanel("Erregerstatistik",
               h3(textOutput("text_erregerstat1")),
               h4(textOutput("text_erregerstat2")),
               hr(),
               htmlOutput("text_zusammenfassung_erreger"),
               hr(),
               DT::dataTableOutput("datatable_erregerstat1")),
      tabPanel("Resistenzstatistik",tabsetPanel( id = "def",
                                               #navbarMenu("Datenblatt Antibiotika",
                                               tabPanel("Datenblatt Antibiotika",
                                                        h6(textOutput("hinweis_tabellen")),
                                                        hr(),
                                                        h3(textOutput("text_zusammenfassung0b")),
                                                        h4(textOutput("text_zusammenfassung0")),
                                                        htmlOutput("text_zusammenfassung0c"),
                                                        hr(),
                                                        uiOutput("datatables_statistik")
                                                        ),
                                               tabPanel("Grafiken Antibiotika",
                                                        h6(textOutput("hinweis_abb")),
                                                        hr(),
                                                        h3(textOutput("text_zusammenfassung0b2")),
                                                        h4(textOutput("text_zusammenfassung02")),
                                                        htmlOutput("text_zusammenfassung0c2"),
                                                        hr(),
                                                        uiOutput("plots_statistik"))
                                               ),
      ),
      tabPanel("Trend-Analyse",
               h6(textOutput("hinweis_tabellen_trend")),
               hr(),
               h3(textOutput("text_trend1")),
               h4(textOutput("text_trend2")),
               hr(),
               htmlOutput("text_zusammenfassung_trend"),
               hr(),
               uiOutput("plots_trend")
      ),
      tabPanel("Cluster-Analyse",tabsetPanel( id = "abc",         
                                    navbarMenu("Unabhängige Analyse pro Spezies",
                                               tabPanel("Heatmap (sortiert: Klinik/Fachbereich, Resistenz)",
                                                        h3(textOutput("text_analyse1a")),
                                                        h4(textOutput("text_analyse1")),
                                                        uiOutput("plots1")),
                                               tabPanel("Heatmap (sortiert: Klinik/Fachbereich, Datum)",
                                                        h3(textOutput("text_analyse2a")),
                                                        h4(textOutput("text_analyse2")),
                                                        uiOutput("plots2")),
                                               tabPanel("Heatmap (hierarchisches Clustering)",
                                                        h3(textOutput("text_analyse3a")),
                                                        h4(textOutput("text_analyse3")),
                                                        uiOutput("plots3")),
                                               tabPanel("UMAP (eingefärbte Kliniken/Fachbereiche)",
                                                        h3(textOutput("text_analyse4a")),
                                                        h4(textOutput("text_analyse4")),
                                                        h6(textOutput("text_analyse4b")),
                                                        uiOutput("plots4")),
                                               tabPanel("UMAP (eingefärbte Cluster)",
                                                        h3(textOutput("text_analyse5a")),
                                                        h4(textOutput("text_analyse5")),
                                                        h6(textOutput("text_analyse5b")),
                                                        uiOutput("plots5")),
                                               tabPanel("Zusätzliche Heatmap (sortiert: UMAP-Cluster)",
                                                        h3(textOutput("text_analyse6a")),
                                                        h4(textOutput("text_analyse6")),
                                                        uiOutput("plots6")),
                                               tabPanel("Zusätzliche Heatmap (sortiert: Klinik/Fachbereich)",
                                                        h3(textOutput("text_analyse6ab")),
                                                        h4(textOutput("text_analyse6b")),
                                                        uiOutput("plots6b"))),
                                    
                                    navbarMenu("Unabhängige Analyse pro Klink/Fachbereich",
                                               tabPanel("Heatmap (sortiert: Spezies)",
                                                        h3(textOutput("text_analyse7a")),
                                                        h4(textOutput("text_analyse7")),
                                                        uiOutput("plots7")),
                                               tabPanel("Heatmap (hierarchisches Clustering)",
                                                        h3(textOutput("text_analyse8a")),
                                                        h4(textOutput("text_analyse8")),
                                                        uiOutput("plots8"))))
               
      )
    )
  )
))





